networks:
    net:
        external: true
services:
    web-service:
        image: hotelaxd
        container_name: hotelaxd
        build: .
        restart: always  # run as a service
        networks:
            net:
                ipv4_address: 192.168.10.200
        volumes:
            - ./storage:/app/storage
            - ./.env:/app/.env

volumes:
    storage:
        driver: local
